name: Delete Merged Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true && (startsWith(github.event.pull_request.head.ref, 'add-plugin-') || startsWith(github.event.pull_request.head.ref, 'add-meta-plugin-'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Delete branch
        run: |
          gh api -X DELETE /repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
